<?php


function martin_webform_cron(){
/*
 * select w.nid, ws.sid, wc.cid, wc.name, wsd.data
from webform w
left join webform_submissions ws on w.nid=ws.nid
left join webform_submitted_data wsd on ws.sid=wsd.sid AND w.nid=wsd.nid
join webform_component wc on wc.cid=wsd.cid
where ws.submitted>now()-interval 7 day and ws.submitted<now()
 */
    $results=db_query("select n.title, w.nid, ws.sid, wc.cid, wc.name, wsd.data
from webform w
left join node n on n.nid=w.nid
left join webform_submissions ws on w.nid=ws.nid
left join webform_submitted_data wsd on ws.sid=wsd.sid AND w.nid=wsd.nid
join webform_component wc on wc.cid=wsd.cid and wc.nid=w.nid
where ws.submitted>now()-interval 7 day and ws.submitted<now()");
    $export=array();
    foreach($results as $r){
        if(!isset($export[$r->title])){
            $export[$r->title]=array();
        }
        if(!isset($export[$r->title][$r->sid])){
            $export[$r->title][$r->sid]=array();
        }

        $export[$r->title][$r->sid][$r->name] = $r->data;
    }


    $filenames=array();
    $attachments=array();

    foreach($export as $webform=>$submissions){
        $file_name = drupal_tempnam('temporary://', 'webform_'.$webform);
        $filenames[]=$file_name;
        $handle = @fopen($file_name, 'w'); // The @ suppresses errors.
        $first=true;
        foreach($submissions as $submission){
            if($first){
               $ak=array_keys($submission);
                fputcsv($handle, $ak);
            }
            fputcsv($handle, $submission);
        }

        fclose($handle);
        $attachments[]=array(
            'filecontent'=>file_get_contents($file_name),
            'filename'=>urlencode($webform).'.csv',
            'filemime'=>'text/csv'
        );


    }


    $mine = variable_get('martin_manager_email');
    $to = $mine; // to e-mail address
    $from = "info@martin-eng.com"; // from e-mail address

    $subject = "text to display in e-mail subject"; // subject of e-mail
    $body = "text to display in e-mail body"; //it might be any variable from the form eg. $form_state['values']['your_field']
  
    

    //params is the array passed to hook_mail function
    $params = array(
        'subject' => $subject,
        'body' => $body,
        'attachments' => $attachments,
        );

    drupal_mail('martin_webform', 'information', $to, language_default(), $params, $from);
}

function martin_webform_mail($key, &$message, $params){
      switch ($key) {
          case "information":
              // Set the mail content type to html to send an html e-mail (optional).
              $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
              // Grab the subject and body from params and add it to the message.
              $message['subject'] = $params['subject'];
              $message['body'][] = $params['body'];
              if (isset($params['attachments'])) {
                  $message['params']['attachments'] = $params['attachments'];
              }
              echo "IN DIS";
              break;
      }
}
