<?php
/**
 * Created by Digital Bridge Solutions.
 * User: DeAndre Elion
 * Email: deandre.elion@dbridgesolutions.com
 * Date: 7/3/14
 */

function content_lock_form_alter(&$form, &$form_state, $form_id) {
    if (($form_id =='webform_client_form_125') || ($form_id == 'webform_client_form_651')) {
    $form['#submit'][] = 'content_lock_lead';
  }    
}

function content_lock_lead(&$form, &$form_state) {

  // to retrieve cookie use $_COOKIE['Drupal_visitor_signup'];
  if(!isset( $_COOKIE['Drupal_visitor_signup'])) {
   // setting drupal cookie, even for anonymous user
    user_cookie_save(array('signup' => 1, 'success' => 1));
  }
}

function content_lock_theme_registry_alter(&$theme_registry) {
  // Defined path to current module.
  $module_path = drupal_get_path('module', 'content_lock');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Itterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key]['type'] = 'module';
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
    }
  }
}